"""Grain/order-swap macros for the DiscrimEval informed-oracle paragraph.

The committed ``informed_oracle`` prediction files store per-item, per-order rates
(``item_rates`` keys ``<template>-o0`` / ``<template>-o1``, sign-canonicalized), so the
A/B order-swap effect is recomputable from artifacts: score each contrast from a single
applicant order vs. from both orders averaged. The third design-phase arm --- differencing
two absolute per-cell predictions (+0.32 macro) --- used a retired method variant with no
surviving artifacts and stays a sourced literal in the text (docs/method-diagnostics.md).

Writes paper/generated/grain.tex. Default pool, dev split, deterministic.
"""
from statistics import mean
from pathlib import Path

import yaml

from behavior_prediction import common, metrics, splits
from behavior_prediction.evals import get_spec

OUT = Path("paper/generated/grain.tex")


def order_macro(pool, spec, man, order: str | None) -> float:
    """Macro dev r over the pool, predictions restricted to one applicant order (or both)."""
    rs = []
    for slug in pool:
        preds_doc = common.load_json(
            Path(f"results/discrimeval/{slug}/predictions/informed_oracle.json"))["predictions"]
        targets = common.load_json(Path(f"results/discrimeval/{slug}/targets.json"))["targets"]
        dev = splits.split_keys(spec, targets, man, "dev")
        preds = {}
        for k, v in preds_doc.items():
            vals = [x for kk, x in v["item_rates"].items()
                    if order is None or kk.endswith(f"-{order}")]
            if vals:
                preds[k] = mean(vals)
        pairs = [v for v in spec.score_contrasts(targets, preds, keys=dev).values()
                 if v[0] is not None and v[1] is not None]
        rs.append(metrics.pearson(pairs))
    return mean(rs)


def main() -> int:
    pool = yaml.safe_load(open("behavior_prediction/models.yaml"))["pools"]["default"]
    spec = get_spec("discrimeval")
    man = splits.load_manifest("discrimeval")
    swapped = order_macro(pool, spec, man, None)
    single = mean([order_macro(pool, spec, man, "o0"), order_macro(pool, spec, man, "o1")])
    lines = [
        "% Auto-generated by scripts/export_grain_macros.py -- DO NOT EDIT BY HAND.",
        "% DiscrimEval informed_oracle, default pool, dev split: macro r scored from a single",
        "% applicant order (mean of the two orders' macros) vs. both orders averaged.",
        f"\\newcommand{{\\grainSingleOrderR}}{{{single:+.2f}}}",
        f"\\newcommand{{\\grainSwappedR}}{{{swapped:+.2f}}}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}: single-order {single:+.3f} -> swapped {swapped:+.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
