#!/usr/bin/env python3
"""Emit paper/generated/table_finetune_full.tex: the full finetune performance table.

One row per (finetune pair, method); each cell is base$\\to$tuned dev $r$ on that evaluation,
plus a macro over the evals scored on both sides of the pair. Source of every number:
results/reports/evaluation_finetunes.json (the `finetunes` pool scoring, noise-ceiling filter
ON — cells the filter dropped are marked, cells never scored are plain '--').

Run after `bp-evaluate --pool finetunes`:
  .venv/bin/python scripts/export_finetune_full.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from behavior_prediction.method_names import SHORT  # noqa: E402

SRC = Path("results/reports/evaluation_finetunes.json")
OUT = Path("paper/generated/table_finetune_full.tex")

# (family display, corpus label, base slug, tuned slug)
PAIRS = [
    ("Gemma-4-31B", "rate", "gemma-4-31b", "gemma-4-31b-selfpred-v1"),
    ("Gemma-4-31B", "residual", "gemma-4-31b", "gemma-4-31b-selfpred-resid"),
    ("Gemma-4-31B", "property", "gemma-4-31b", "gemma-4-31b-intro30k"),
    ("Qwen2.5-72B", "rate", "qwen2.5-72b", "qwen2.5-72b-selfpred-v1"),
    ("Llama-3.3-70B", "rate", "llama-3.3-70b-tg", "llama-3.3-70b-selfpred-v2fix-tg"),
    ("Llama-3.3-70B", "residual", "llama-3.3-70b-tg", "llama-3.3-70b-selfpred-resid-tg"),
    ("DeepSeek-V4-Flash", "rate", "deepseek-v4-flash-off-tg", "deepseek-v4-flash-selfpred-v1-tg"),
    ("DeepSeek-V4-Flash", "residual", "deepseek-v4-flash-off-tg",
     "deepseek-v4-flash-selfpred-resid-tg"),
    ("DeepSeek-V4-Flash", "property", "deepseek-v4-flash-off-tg", "deepseek-v4-flash-intro30k-tg"),
]

METHODS = ["self_report", "informed_oracle", "pairwise"]

EVALS = [
    ("sycophancy_pushback", "Sycophancy"),
    ("discrimeval", "DiscrimEval"),
    ("capability_mmlu", "Capability"),
    ("propensitybench", "PropB"),
]


def main() -> None:
    d = json.loads(SRC.read_text())
    cells = {(c["model"], c["eval"], c["method"]): c["r"] for c in d["cells"]}
    dropped = {(w["eval"], w["model"]) for w in d["dropped_weak"]}

    def cell(base: str, tuned: str, ev: str, meth: str) -> str:
        rb, rt = cells.get((base, ev, meth)), cells.get((tuned, ev, meth))
        if rb is None or rt is None:
            ceilinged = (ev, base) in dropped or (ev, tuned) in dropped
            return r"--\,$^\dagger$" if ceilinged else "--"
        return f"{rb:+.2f}$\\,\\to\\,${rt:+.2f}"

    lines = [
        "% Auto-generated by scripts/export_finetune_full.py -- DO NOT EDIT BY HAND.",
        r"\begin{table}[t]", r"  \centering",
        r"  \caption{Every self-prediction finetune pair on every evaluation where both the base "
        r"and the tuned model are scored (dev split, tuned settings; cells are base$\,\to\,$tuned "
        r"$r$; macro averages the evaluations scored on both sides of that row). Corpora: "
        r"\emph{rate} = absolute agree-rate self-prediction; \emph{residual} = signed "
        r"deviation-from-donor-mean (\S\ref{app:selfpred}); \emph{property} = Binder-style "
        r"hypothetical-response prediction (intro30k). '--' = not scored; "
        r"$^\dagger$ = dropped by the noise-ceiling filter (behavior too unreliable to score). "
        r"The only consistent paired-comparison movement is the Gemma family's PropensityBench "
        r"gain; elsewhere its changes are within noise.}",
        r"  \label{tab:finetune-full}", r"  \scriptsize",
        r"  \setlength{\tabcolsep}{2.5pt}",
        r"  \begin{tabular}{llccccc}", r"    \toprule",
        r"    Finetune & Method & " + " & ".join(h for _, h in EVALS) + r" & Macro \\",
        r"    \midrule",
    ]

    n_rows = 0
    for i, (family, corpus, base, tuned) in enumerate(PAIRS):
        if i:
            lines.append(r"    \midrule")
        for j, meth in enumerate(METHODS):
            label = f"{family} ({corpus})" if j == 0 else ""
            row = [cell(base, tuned, ev, meth) for ev, _ in EVALS]
            both = [(cells[(base, ev, meth)], cells[(tuned, ev, meth)]) for ev, _ in EVALS
                    if (base, ev, meth) in cells and (tuned, ev, meth) in cells]
            if both:
                mb = sum(b for b, _ in both) / len(both)
                mt = sum(t for _, t in both) / len(both)
                macro = f"{mb:+.2f}$\\,\\to\\,${mt:+.2f}"
            else:
                macro = "--"
            lines.append(f"    {label} & {SHORT[meth]} & " + " & ".join(row)
                         + f" & {macro} \\\\")
            n_rows += 1

    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({n_rows} rows, {len(PAIRS)} pairs)")


if __name__ == "__main__":
    main()
