#!/usr/bin/env python3
"""Emit paper/generated/selfpred.tex from the self-prediction finetuning reports.

Two tables, both auto-generated so the paper never carries hand-typed numbers:
  1. Fixed-point / self-knowledge per base model (from results/reports/selfpred_finetune_<m>.json).
  2. The DiscrimEval self_report gain vs the cross_model_mean predictability control (from the
     per-pair eval-pool JSONs), which separates a genuine self-specific gain from behavior merely
     becoming more typical of the pool.

The row lists below are the single registry of scoreable finetunes — add a row here when a new
base's report / pair pool lands (pair pools are generated with
``bp-evaluate --pool <pair> --no-filter-weak``; the residual is a within-model delta, so the
pool-level ceiling filter would only punch holes in it).

Run after the reports and the base/tuned eval-pool scorings exist:
  .venv/bin/python scripts/export_selfpred_paper.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPORTS = Path("results/reports")

# --- Table 1 rows: (display name, report stem) — the rate-corpus fixed-point reports. ---
FIXEDPOINT_ROWS = [
    ("Llama-3.3-70B", "selfpred_finetune_llama_v2fix"),
    ("Gemma-4-31B", "selfpred_finetune_gemma"),
    ("Qwen2.5-72B", "selfpred_finetune_qwen72"),
    ("DeepSeek-V4-Flash", "selfpred_finetune_deepseek"),
]

# --- Table 2 rows: (display name, corpus label, pair-pool JSON, base slug, tuned slug). ---
RESIDUAL_ROWS = [
    ("Llama-3.3-70B", "rate corpus",
     "evaluation_llamav2fixpair.json", "llama-3.3-70b-tg", "llama-3.3-70b-selfpred-v2fix-tg"),
    ("Gemma-4-31B", "rate corpus",
     "evaluation_gemmapair.json", "gemma-4-31b", "gemma-4-31b-selfpred-v1"),
    ("Qwen2.5-72B", "rate corpus",
     "evaluation_qwen72pair.json", "qwen2.5-72b", "qwen2.5-72b-selfpred-v1"),
    ("DeepSeek-V4-Flash", "rate corpus",
     "evaluation_deepseekpair.json", "deepseek-v4-flash-off-tg", "deepseek-v4-flash-selfpred-v1-tg"),
    ("Gemma-4-31B", "residual corpus",
     "evaluation_gemmaresidpair.json", "gemma-4-31b", "gemma-4-31b-selfpred-resid"),
    ("Llama-3.3-70B", "residual corpus",
     "evaluation_llamaresidpair.json", "llama-3.3-70b-tg", "llama-3.3-70b-selfpred-resid-tg"),
    ("DeepSeek-V4-Flash", "residual corpus",
     "evaluation_deepseekresidpair.json", "deepseek-v4-flash-off-tg",
     "deepseek-v4-flash-selfpred-resid-tg"),
]


def _f(x: float | None, s: str = "+.3f") -> str:
    return "--" if x is None else format(x, s)


def _cells(path: Path) -> dict:
    d = json.loads(path.read_text())
    return {(c["model"], c["eval"], c["method"]): c["r"] for c in d["cells"]}


def main() -> None:
    lines = ["% Auto-generated by scripts/export_selfpred_paper.py -- DO NOT EDIT BY HAND.", ""]

    # --- Table 1: fixed-point / self-knowledge ---
    lines += [
        r"\begin{table}[t]", r"  \centering",
        r"  \caption{Self-prediction finetuning, one round of "
        r"$G(M)=\mathrm{finetune}(M_0,\mathrm{behavior}(M))$, on held-out categories "
        r"($n{=}40$; gap correlation, noise ceiling $\approx 0.98$). \textbf{Base self} and "
        r"\textbf{tuned self}: how well each model predicts its \emph{own} acquiescence gap. "
        r"\textbf{Drift} $|\Delta\mathrm{gap}|$: how much the finetune moved the model's own "
        r"behavior. Convergence tracks drift: the less behavior moves, the closer tuned self-"
        r"prediction gets to the training target (tuned vs.\ base behavior).}",
        r"  \label{tab:selfpred-fixedpoint}", r"  \footnotesize",
        r"  \begin{tabular}{lcccc}", r"    \toprule",
        r"    Base model & Base self & Tuned self & Tuned vs.\ target & Drift $|\Delta\mathrm{gap}|$ \\",
        r"    \midrule",
    ]
    n_fixed = 0
    for name, stem in FIXEDPOINT_ROWS:
        path = REPORTS / f"{stem}.json"
        if not path.exists():
            print(f"  [skip] table 1 row {name}: {path} missing")
            continue
        d = json.loads(path.read_text())
        sk = d["self_knowledge"]
        dr = d["drift"]
        lines.append(
            f"    {name} & {_f(sk['base_vs_own_behavior'])} & "
            f"\\textbf{{{_f(sk['tuned_vs_own_behavior'])}}} & "
            f"{_f(dr['tuned_pred_vs_base_behavior_gap_r'])} & "
            f"{_f(dr['mean_abs_delta_gap'], '.3f')} \\\\")
        n_fixed += 1
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]

    # --- Table 2: DiscrimEval gain vs the predictability control ---
    lines += [
        r"\begin{table}[t]", r"  \centering",
        r"  \caption{DiscrimEval \texttt{self\_report} gain after self-prediction finetuning, "
        r"controlled against \texttt{cross\_model\_mean} (a predictor that never consults the model, "
        r"so $\Delta$ measures behavior becoming more typical of the pool). The \textbf{residual} "
        r"$\Delta\texttt{self\_report}-\Delta\texttt{cross\_model\_mean}$ is the self-specific gain. "
        r"The rate self-prediction corpus yields a positive residual on every base; the "
        r"residual-target corpus (\S\ref{app:selfpred}) amplifies it on Gemma but not uniformly "
        r"--- DeepSeek's residual-corpus row is null. (The Binder-style property finetune"
        r"~\citep{binder2024looking} on Llama, not shown, has essentially zero residual --- its "
        r"raw gain is entirely increased predictability.)}",
        r"  \label{tab:selfpred-residual}", r"  \footnotesize",
        r"  \begin{tabular}{lccc}", r"    \toprule",
        r"    Finetune & $\Delta$\texttt{self\_report} & $\Delta$\texttt{xmm} & Residual \\",
        r"    \midrule",
    ]
    n_resid = 0
    prev_corpus = None
    for name, corpus, pool, base, tuned in RESIDUAL_ROWS:
        path = REPORTS / pool
        if not path.exists():
            print(f"  [skip] table 2 row {name} ({corpus}): {path} missing")
            continue
        c = _cells(path)
        e = "discrimeval"
        vals = [c.get((tuned, e, "self_report")), c.get((base, e, "self_report")),
                c.get((tuned, e, "cross_model_mean")), c.get((base, e, "cross_model_mean"))]
        if any(v is None for v in vals):
            print(f"  [skip] table 2 row {name} ({corpus}): discrimeval cells incomplete")
            continue
        dsr = vals[0] - vals[1]
        dxm = vals[2] - vals[3]
        if prev_corpus is not None and corpus != prev_corpus:
            lines.append(r"    \midrule")
        prev_corpus = corpus
        lines.append(f"    {name} ({corpus}) & {_f(dsr)} & {_f(dxm)} & "
                     f"\\textbf{{{_f(dsr - dxm)}}} \\\\")
        n_resid += 1
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]

    out = Path("paper/generated/selfpred.tex")
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({n_fixed} fixed-point rows, {n_resid} residual rows)")


if __name__ == "__main__":
    main()
