"""Identity transfer for the oracle pair: does the SELF-framed oracle predict its own behavior
better than others', and does the GENERIC-framed one lose that?

Writes results/reports/oracle_identity_transfer{_test}.txt (the report below) and
paper/generated/identity_transfer{_test}.tex (the \\idt* macros quoted in the intro and
sec:results-generic). Run with --split test to refresh the paper's numbers; the test run also
recomputes the dev pooled advantage so the body's dev-vs-test sentence is fully macro-backed.
"""
import argparse, itertools, sys
from pathlib import Path
from statistics import mean
import yaml
sys.path.insert(0, ".")
from behavior_prediction import common, metrics, splits
from behavior_prediction.evals import get_spec

_ap = argparse.ArgumentParser()
_ap.add_argument("--split", choices=["dev", "test"], default="dev")
SPLIT = _ap.parse_args().split
_sfx = "" if SPLIT == "dev" else "_test"
OUT_TXT = Path(f"results/reports/oracle_identity_transfer{_sfx}.txt")
OUT_TEX = Path(f"paper/generated/identity_transfer{_sfx}.tex")

EVALS = ["discrimeval","propensitybench","capability_mmlu","sycophancy_pushback","reward_hacking","tau2_policy"]
POOL = list(yaml.safe_load(open("behavior_prediction/models.yaml"))["pools"]["default"])
METHODS = ("informed_oracle", "generic_oracle")
# macro tag per method / per eval, so \idt<Method><Eval><Stat> is stable across runs
MTAG = {"informed_oracle": "Oracle", "generic_oracle": "Generic"}
# digits are illegal in LaTeX macro names, so tau2_policy -> TauPolicy
ETAG = {e: "".join(p.capitalize() for p in e.replace("tau2", "tau").split("_")) for e in EVALS}

def tuned(ev, m):
    try:
        return common.load_json(Path(f"results/{ev}/tuning.json"))["methods"][m]["best_setting"]
    except Exception:
        return m

def preds(ev, slug, fname):
    p = Path(f"results/{ev}/{slug}/predictions/{fname}.json")
    if not p.exists(): return {}
    return {k: v.get("predicted_rate") for k, v in common.load_json(p)["predictions"].items()
            if isinstance(v, dict) and v.get("predicted_rate") is not None}

def actuals(spec, ev, slug, split):
    t = common.load_json(Path(f"results/{ev}/{slug}/targets.json"))["targets"]
    keys = set(splits.split_keys(spec, t, splits.load_manifest(ev), split))
    if getattr(spec, "scoring_semantics","") == "bias_contrast":
        sc = spec.score_contrasts(t, {k: v.get("rate") for k,v in t.items()}, keys=keys)
        return {k: a for k,(a,_) in sc.items() if a is not None}
    return {k: v["rate"] for k,v in t.items() if k in keys and v.get("rate") is not None}

def transfer(split):
    """{method: (pooled diag, off, advantage, n_diag, n_off, {eval: (diag, off, adv)})}."""
    out = {}
    for method in METHODS:
        D, O, per_eval = [], [], {}
        for ev in EVALS:
            spec = get_spec(ev); f = tuned(ev, method)
            act = {s: actuals(spec, ev, s, split) for s in POOL
                   if Path(f"results/{ev}/{s}/targets.json").exists()}
            pv  = {s: preds(ev, s, f) for s in act}
            d, o = [], []
            for a, b in itertools.product(act, act):
                if not pv.get(a): continue
                ks = sorted(set(pv[a]) & set(act[b]))
                r = metrics.pearson([(act[b][k], pv[a][k]) for k in ks]) if len(ks)>=3 else None
                if r is None: continue
                (d if a==b else o).append(r)
            if d and o:
                per_eval[ev] = (mean(d), mean(o), mean(d)-mean(o))
                D += d; O += o
        out[method] = (mean(D), mean(O), mean(D)-mean(O), len(D), len(O), per_eval)
    return out

tot = transfer(SPLIT)

lines = [f"Identity transfer, {SPLIT} split, default pool.",
         f"{'method':<18}{'eval':<22}{'diag':>7}{'off':>7}{'advantage':>11}"]
for method, (_, _, _, _, _, per_eval) in tot.items():
    for ev, (d, o, adv) in per_eval.items():
        lines.append(f"{method:<18}{ev:<22}{d:+7.2f}{o:+7.2f}{adv:+11.2f}")
lines.append("")
for m, (d, o, adv, nd, no, _) in tot.items():
    lines.append(f"POOLED {m:<18} diag {d:+.2f} (n={nd})  off {o:+.2f} (n={no})  "
                 f"self-advantage {adv:+.2f}")

# The body contrasts this split's advantage with the dev one, so a test run carries both.
dev_adv = None
if SPLIT == "test":
    dev_adv = transfer("dev")["informed_oracle"][2]
    lines.append(f"(dev pooled self-advantage, informed_oracle: {dev_adv:+.2f})")

tex = [f"% Auto-generated by scripts/oracle_identity_transfer.py --split {SPLIT}"
       " -- DO NOT EDIT BY HAND.",
       "% Model A's self-predictions scored against model B's behavior: Diag = A==B (own),",
       "% Off = A!=B (others'), Adv = Diag - Off. Pearson r, macro over (predictor, target)",
       "% pairs; weak cells are those with <3 shared conditions."]
for method, (d, o, adv, nd, no, per_eval) in tot.items():
    t = MTAG[method]
    tex += [f"\\newcommand{{\\idt{t}Diag}}{{{d:+.2f}}}",
            f"\\newcommand{{\\idt{t}Off}}{{{o:+.2f}}}",
            f"\\newcommand{{\\idt{t}Adv}}{{{adv:+.2f}}}",
            f"\\newcommand{{\\idt{t}NDiag}}{{{nd}}}",
            f"\\newcommand{{\\idt{t}NOff}}{{{no}}}"]
    for ev, (ed, eo, eadv) in per_eval.items():
        tex += [f"\\newcommand{{\\idt{t}{ETAG[ev]}Diag}}{{{ed:+.2f}}}",
                f"\\newcommand{{\\idt{t}{ETAG[ev]}Off}}{{{eo:+.2f}}}",
                f"\\newcommand{{\\idt{t}{ETAG[ev]}Adv}}{{{eadv:+.2f}}}"]
if dev_adv is not None:
    tex.append(f"\\newcommand{{\\idtOracleAdvDev}}{{{dev_adv:+.2f}}}")

print("\n".join(lines))
OUT_TXT.parent.mkdir(parents=True, exist_ok=True)
OUT_TXT.write_text("\n".join(lines) + "\n")
OUT_TEX.write_text("\n".join(tex) + "\n")
print(f"\nWrote {OUT_TXT} and {OUT_TEX}")
