"""Tuning-sensitivity check (Option C): how much could per-cell setting choice matter?

The headline numbers score every model at the setting frozen on the selection pool. This
script bounds the possible handicap: for each (eval, model, method) cell with more than one
grid arm on disk, compare the tuned arm's dev r with the best arm chosen per cell in
hindsight. The delta is an UPPER bound on what per-model tuning could add (in-sample choice).

Runs over whichever pool is passed (--pool small by default: the six original models carry
full grids; frontier settings were elicited at tuned arms only, so their counter-arms must
be elicited before this bounds them directly).

Writes results/reports/tuning_sensitivity_<pool>.txt and (for pool 'small')
paper/generated/tuning_sensitivity.tex.
"""
import argparse
from pathlib import Path
from statistics import mean

import yaml

from behavior_prediction import common, metrics, splits
from behavior_prediction.evals import get_spec

EVALS = ["discrimeval", "propensitybench", "capability_mmlu", "sycophancy_pushback",
         "reward_hacking", "tau2_policy"]
# Swept methods and every arm id ever generated for them (list_experiment excluded from the
# merged-pool design; value's sweep was retired by design, included here for completeness).
ARMS = {
    "self_report": ["self_report", "self_report-honest"],
    "pairwise": ["pairwise", "pairwise-indiff"],
    "llm_prediction": ["llm_prediction", "llm_prediction-full"],
    "oracle_xmm_learned": ["oracle_xmm_learned", "oracle_xmm_learned-full"],
}


def tuned(ev, m):
    try:
        return common.load_json(Path(f"results/{ev}/tuning.json"))["methods"][m]["best_setting"]
    except Exception:
        return m


def cell_r(spec, ev, slug, fname, targets, dev):
    p = Path(f"results/{ev}/{slug}/predictions/{fname}.json")
    if not p.exists():
        return None
    preds = {k: v.get("predicted_rate") for k, v in common.load_json(p)["predictions"].items()
             if isinstance(v, dict) and v.get("predicted_rate") is not None}
    if getattr(spec, "scoring_semantics", "") == "bias_contrast":
        pairs = [v for v in spec.score_contrasts(targets, preds, keys=dev).values()
                 if v[0] is not None and v[1] is not None]
    else:
        pairs = [(t["rate"], preds[k]) for k, t in targets.items()
                 if k in dev and t.get("rate") is not None and preds.get(k) is not None]
    return metrics.pearson(pairs) if len(pairs) >= 5 else None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pool", default="small")
    args = ap.parse_args()
    pool = yaml.safe_load(open("behavior_prediction/models.yaml"))["pools"][args.pool]

    lines = [f"pool={args.pool}: tuned-arm r -> best-arm r per cell (hindsight bound)",
             f"{'method':<20}{'eval':<22}{'cells':>6}{'mean tuned':>11}{'mean best':>11}"
             f"{'mean delta':>11}{'max delta':>10}"]
    per_method = {}
    for method, arms in ARMS.items():
        deltas_all = []
        for ev in EVALS:
            spec = get_spec(ev)
            man = splits.load_manifest(ev)
            tuned_arm = tuned(ev, method)
            rows = []
            for slug in pool:
                tp = Path(f"results/{ev}/{slug}/targets.json")
                if not tp.exists():
                    continue
                targets = common.load_json(tp)["targets"]
                dev = set(splits.split_keys(spec, targets, man, "dev"))
                r_tuned = cell_r(spec, ev, slug, tuned_arm, targets, dev)
                alts = [r for a in arms
                        if (r := cell_r(spec, ev, slug, a, targets, dev)) is not None]
                if r_tuned is None or len(alts) < 2:   # need at least one real alternative
                    continue
                rows.append((r_tuned, max(alts)))
            if rows:
                mt, mb = mean(r for r, _ in rows), mean(b for _, b in rows)
                ds = [b - r for r, b in rows]
                deltas_all += ds
                lines.append(f"{method:<20}{ev:<22}{len(rows):>6}{mt:>+11.2f}{mb:>+11.2f}"
                             f"{mean(ds):>+11.2f}{max(ds):>+10.2f}")
        if deltas_all:
            per_method[method] = (mean(deltas_all), max(deltas_all), len(deltas_all))
    lines.append("")
    for m, (md, xd, n) in per_method.items():
        lines.append(f"OVERALL {m:<20} mean delta {md:+.3f}  max {xd:+.3f}  over {n} cells")
    out = Path(f"results/reports/tuning_sensitivity_{args.pool}.txt")
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {out}")

    if args.pool == "small" and per_method:
        tex = ["% Auto-generated by scripts/tuning_sensitivity.py -- DO NOT EDIT BY HAND.",
               "% Hindsight bound: per-cell best grid arm minus the frozen tuned arm."]
        for m, (md, xd, n) in per_method.items():
            tag = "".join(w.capitalize() for w in m.split("_"))
            tex.append(f"\\newcommand{{\\tsens{tag}Mean}}{{{md:+.2f}}}")
            tex.append(f"\\newcommand{{\\tsens{tag}Max}}{{{xd:+.2f}}}")
            tex.append(f"\\newcommand{{\\tsens{tag}N}}{{{n}}}")
        Path("paper/generated/tuning_sensitivity.tex").write_text("\n".join(tex) + "\n")
        print("Wrote paper/generated/tuning_sensitivity.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
